language: java
sudo: required
install: true

services:
  - docker
  - postgresql
jdk:
  - oraclejdk8

notifications:
  email: false

before_script:
  - sudo travis/travis_before.sh

script:
  - sudo mvn clean install
  - sudo docker-compose build

# trigger code-coverage service
after_success:
  - bash <(curl -s https://codecov.io/bash) -t 24a90402-c015-43ce-83cb-d95aa82b388c