language: java
sudo: required
install: true

services:
  - docker
  - postgresql
jdk:
  - oraclejdk8

notifications:
  email: false

before_script:
  - sudo travis/travis_before.sh

script:
  - sudo mvn clean install
  - sudo docker-compose build